name: flutter_basic_lib
description: Flutter项目开发脚手架
version: 0.0.1
homepage: https://github.com/azhon/TODO-Flutter

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #  路由
  fluro: ^2.0.3
  #  屏幕适配
  flutter_screenutil: ^5.5.3+2
  #  图片库
  extended_image: ^6.2.1
  #  bloc状态管理
  flutter_bloc: ^8.0.1
  #  网络库
  dio: ^4.0.6
  #  日志
  logger: ^1.1.0
  #  刷新
  pull_to_refresh: ^2.0.0
  # 本地存储
  shared_preferences: ^2.0.15
  #  toast
  fluttertoast: ^8.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
